// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ2y3ks3HHOKDzA0egLJkvKIRJkznk35A',
    appId: '1:297181108181:web:67d3ddd40ee344e2170f5c',
    messagingSenderId: '297181108181',
    projectId: 'fruithub-f488a',
    authDomain: 'fruithub-f488a.firebaseapp.com',
    storageBucket: 'fruithub-f488a.firebasestorage.app',
    measurementId: 'G-JMYBKV09J7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1xedfyuufyk7MLXmbYiAjLoBy4glh8L4',
    appId: '1:297181108181:android:3d035bfa1a78547c170f5c',
    messagingSenderId: '297181108181',
    projectId: 'fruithub-f488a',
    storageBucket: 'fruithub-f488a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBufS8IpvcnakLViHU0OOtUWK-4m2VQX0I',
    appId: '1:297181108181:ios:e19493f417420a6a170f5c',
    messagingSenderId: '297181108181',
    projectId: 'fruithub-f488a',
    storageBucket: 'fruithub-f488a.firebasestorage.app',
    androidClientId: '297181108181-nsm79kfpsqbd60gjjbdpmbqmaa2bn5n5.apps.googleusercontent.com',
    iosClientId: '297181108181-b71imlhnjspq06k7ceb82cvudsn95ss4.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitHubDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBufS8IpvcnakLViHU0OOtUWK-4m2VQX0I',
    appId: '1:297181108181:ios:e19493f417420a6a170f5c',
    messagingSenderId: '297181108181',
    projectId: 'fruithub-f488a',
    storageBucket: 'fruithub-f488a.firebasestorage.app',
    androidClientId: '297181108181-nsm79kfpsqbd60gjjbdpmbqmaa2bn5n5.apps.googleusercontent.com',
    iosClientId: '297181108181-b71imlhnjspq06k7ceb82cvudsn95ss4.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitHubDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJ2y3ks3HHOKDzA0egLJkvKIRJkznk35A',
    appId: '1:297181108181:web:dec9ccae968a0182170f5c',
    messagingSenderId: '297181108181',
    projectId: 'fruithub-f488a',
    authDomain: 'fruithub-f488a.firebaseapp.com',
    storageBucket: 'fruithub-f488a.firebasestorage.app',
    measurementId: 'G-P4FKVDBH0M',
  );
}
